### ISSUE TITLE
[Feature Request] Add support for the `calendar` entity

### ISSUE THREAD

**Issue by andrewjswan** [strange-v/power-outage-schedule-card#1]
Add support for the calendar entity, with the ability to determine the state when the light will be off, possibly off, or there will be no shutdowns.
Examples for calendars:

https://github.com/szheliab/dtek-blackout-schedule-calendars
```yaml
type: custom:power-outage-schedule-card
calendar_entity: calendar.blackout_schedule
hide_past_hours: true
title: Power outage schedule
states:
  - off: Планове відключення
  - maybe: Можливо відключення
```

https://gitlab.com/m03geek/dtek-blackout-schedule/
```yaml
type: custom:power-outage-schedule-card
calendar_entity: calendar.blackout_schedule
hide_past_hours: true
title: Power outage schedule
states:
  - on: no
  - off: yes
  - maybe: maybe
```
